export const MEETUP_GET_SUCCESS = 'MEETUP_GET_SUCCESS';
export const MEETUP_GET_FAILURE = 'MEETUP_GET_FAILURE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';